
version: '3.6'
services:
  telegraf:
    image: arm32v7/telegraf  #Replace with correct image - can use telegraf:latest
    container_name: telegraf
    restart: always
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro #path to your telegraf conf in this scenario it is mapped from the location where this docker compose is run
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'

  influxdb:
    image: arm32v7/influxdb #Replace with correct image - can use influxdb:latest
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=Homekit
      - INFLUXDB_ADMIN_USER=YOURUSER
      - INFLUXDB_ADMIN_PASSWORD=YOUR_PASSWORF
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=YOUR_USER
      - GF_SECURITY_ADMIN_PASSWORD=YOUR_PASSWORD
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      
volumes:
  grafana_data: {}
  influxdb_data: {}

